- type: job
  id: MailCarrier
  name: job-name-mail-carrier
  description: job-description-mail-carrier
  startingGear: CourierGear
  playTimeTracker: JobMailCarrier
  icon: "JobIconMailCarrier"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Mail
  requirements:
    - !type:CharacterEmployerRequirement
      employers:
      - NEWSTAR
#Encore edit- adjusted to fix compiling. Needs role assigned to proper employer later.
- type: startingGear
  id: MailCarrierGear
  subGear:
  - MailCarrierPlasmamanGear
  equipment:
    head: ClothingHeadMailCarrier
    jumpsuit: ClothingUniformMailCarrier
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: MailCarrierPDA
    ears: ClothingHeadsetCargo
    belt: MailBag

- type: startingGear
  id: MailCarrierPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMailCarrier
    head: ClothingHeadEnvirohelmMailCarrier
    gloves: ClothingHandsGlovesEnviroglovesWhite
