- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Psychologist
  extendedAccess:
  - Chemistry
  requirements:
  - !type:CharacterEmployerRequirement
    employers:
    - NEWSTAR
#Encore edit- adjusted to fix compiling. Needs role assigned to proper employer later.
- type: startingGear
  id: PsychologistGear
  subGear:
  - PsychologistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
    back: ClothingBackpackMedical
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  storage:
    back:
    - RubberStampPsychologist

- type: startingGear
  id: PsychologistPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitEnviroslacksPsychologist
    head: ClothingHeadEnvirohelmMedicalDoctor
    gloves: ClothingHandsGlovesEnviroglovesWhite
