- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Civilian
    min: 3600 #DeltaV
  - !type:CharacterEmployerRequirement
    employers:
    - NEWSTAR
#Encore edit- adjusted to fix compiling. Needs role assigned to proper employer later.
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics

- type: startingGear
  id: BartenderGear
  subGear:
  - BartenderPlasmamanGear
  equipment:
    head: ClothingHeadHatTophat
    jumpsuit: ClothingUniformJumpsuitBartender
    outerClothing: ClothingOuterVest
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService

- type: startingGear
  id: BartenderPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitEnviroslacks
    head: ClothingHeadEnvirohelmColorWhite
    gloves: ClothingHandsGlovesEnviroglovesWhite
